apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: {{.Values.image.repository}}:{{.Values.image.dockerImageTag}}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-registry2
